# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: CI-CD

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
   - stage: CI
     displayName: 'CI - Pipeline de CI'
     jobs:
     - job: Build
       displayName: 'Build e Testes do Projeto'
       steps:  
        - task: DotNetCoreCLI@2
          inputs:
            azureSubscription: 'Azure subscription 1(1)(7c2c3e39-4083-45dc-8cb9-8b00539e5f73)'
            command: 'build'
            projects: './Backend/API/FinanceControl.sln'
     
        - task: DotNetCoreCLI@2
          inputs:
            azureSubscription: 'Azure subscription 1(7c2c3e39-4083-45dc-8cb9-8b00539e5f73)'
            command: 'test'
            projects: './Backend/FinanceControl.Tests/FinanceControl.Tests.csproj'


    